apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{rolebindingname}"
  annotations:
    expirytime: "{expirytime}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readwrite-role
subjects:
- kind: User
  name: "{user}"
  namespace: default